spring.application.name=foodshare

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/foodshare





spring.security.user.name=user

#logging
#logging.level.com.humber.foodshare.services.MyUserDetailService=INFO
#logging.file.name=logs/spring-boot-application.log