spring.application.name=foodshare

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# MongoDB cluster connection
#spring.data.mongodb.uri=mongodb+srv://jonathanpipim:wolf1234@cluster0.cs5xi.mongodb.net/foodshare?retryWrites=true&w=majority
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.data.mongodb.database=foodshare
spring.data.mongodb.auto-index-creation=true
spring.security.user.name=user

#logging
#logging.level.com.humber.foodshare.services.MyUserDetailService=INFO
#logging.file.name=app/logs/spring-boot-application.log
#logging.level.org.springframework.security=DEBUG

